// export { default as BgLogo } from "./BgLogo";
// export { default as LogoLogin } from "./LogoLogin";
// export { default as SwimmingIcon } from "./swimming.svg";

export { default as PictureIcon } from "./picture.svg?react";
export { default as MainIcon } from "./main.svg?react";
export { default as FireIcon } from "./run.svg?react";
export { default as LinkIcon } from "./link.svg?react";
export { default as RunIcon } from "./run.svg?react";
export { default as SearchIcon } from "./search.svg?react";
export { default as UserIcon } from "./user.svg?react";
export { default as SwimmingIcon } from "./swimming.svg?react";
export { default as HideIcon } from "./hide.svg?react";
export { default as EyeIcon } from "./eye.svg?react";
export { default as HomeIcon } from "./home.svg?react";
export { default as MessageIcon } from "./message.svg?react";
export { default as CheckIcon } from "./check.svg?react";
export { default as SendIcon } from "./send.svg?react";
export { default as LoadingIcon } from "./loading.svg?react";
export { default as TennisRacketIcon } from "./tennisRacket.svg?react";
export { default as BadmintonIcon } from "./badminton.svg?react";
export { default as BasketballIcon } from "./basketball.svg?react";
export { default as BowlingIcon } from "./bowling.svg?react";
export { default as DancinggIcon } from "./dancing.svg?react";
export { default as DumbellsIcon } from "./dumbells.svg?react";
export { default as EllipicalIcon } from "./elliptical.svg?react";
export { default as FencingIcon } from "./fencing.svg?react";
export { default as FitnessIcon } from "./fitness.svg?react";
export { default as GolfIcon } from "./golf.svg?react";
export { default as HollaHoopgIcon } from "./hollaHoop.svg?react";
export { default as JumpRoopIcon } from "./jumpRoop.svg?react";
export { default as MoreCircleIcon } from "./moreCircle.svg?react";
export { default as PiaonIcon } from "./piano.svg?react";
export { default as RollerStakeIcon } from "./rollerStake.svg?react";
export { default as SoccerIcon } from "./soccer.svg?react";
export { default as TableTennisIcon } from "./tableTennis.svg?react";
export { default as TennisIcon } from "./tennis.svg?react";
export { default as VolleyballIcon } from "./volleyball.svg?react";
export { default as WarriorIcon } from "./warrior.svg?react";
export { default as YogaMatIcon } from "./yogaMat.svg?react";
export { default as Popular1Icon } from "./popular1.svg?react";
export { default as Popular2Icon } from "./popular2.svg?react";
export { default as Popular3Icon } from "./popular3.svg?react";


